Actualización Cancelacion, validación, UT
lunasoft/sw-sdk-visual-fox-pro pull request #5
Opened 2022-02-21 05:23 UTC by martinfnsw

Actualización cancelación
Actualización UT
Remover LCO LRFC
Actualización validación

2022-02-21 17:01 UTC, JuanGamezSW approved these changes

2022-02-21 19:50 UTC, SwAeyrton requested changes
Lo que está en la documentación no coincide con lo que está en el código.

2022-02-23 00:36 UTC, crobertor84 commented
.

2022-02-23 15:21 UTC, SwAeyrton approved these changes

2022-02-23 15:39 UTC, martinfnsw commented
Actualización VFP

2022-02-23 15:40 UTC, merged